namespace hlsmx
{
    partial class OptionsForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) { components.Dispose(); }
            base.Dispose(disposing);
        }

private void InitializeComponent()
        {
            this.tabs = new hlsmx.ThemedTabControl();
            this.tabGeneral = new System.Windows.Forms.TabPage();
            this.tabAppearance = new System.Windows.Forms.TabPage();
            this.tabNotifications = new System.Windows.Forms.TabPage();
            this.tabService = new System.Windows.Forms.TabPage();
            this.labelInterval = new System.Windows.Forms.Label();
            this.labelProcessRetries = new System.Windows.Forms.Label();
            this.labelNetworkRetries = new System.Windows.Forms.Label();
            this.labelMaxRestarts = new System.Windows.Forms.Label();
            this.labelCrashLimit = new System.Windows.Forms.Label();
            this.labelShutdown = new System.Windows.Forms.Label();
            this.numInterval = new System.Windows.Forms.NumericUpDown();
            this.numProcessRetries = new System.Windows.Forms.NumericUpDown();
            this.numNetworkRetries = new System.Windows.Forms.NumericUpDown();
            this.numMaxRestarts = new System.Windows.Forms.NumericUpDown();
            this.numCrashLimit = new System.Windows.Forms.NumericUpDown();
            this.numShutdown = new System.Windows.Forms.NumericUpDown();
            this.checkTray = new System.Windows.Forms.CheckBox();
            this.checkBoxLocalIps = new System.Windows.Forms.CheckBox();
            this.buttonImport = new System.Windows.Forms.Button();
            this.listViewHooks = new System.Windows.Forms.ListView();
            this.buttonHookAdd = new System.Windows.Forms.Button();
            this.buttonHookEdit = new System.Windows.Forms.Button();
            this.buttonHookRemove = new System.Windows.Forms.Button();
            this.labelLanguage = new System.Windows.Forms.Label();
            this.comboLanguage = new System.Windows.Forms.ComboBox();
            this.labelTheme = new System.Windows.Forms.Label();
            this.comboTheme = new System.Windows.Forms.ComboBox();
            this.labelIcon = new System.Windows.Forms.Label();
            this.comboIcon = new System.Windows.Forms.ComboBox();
            this.iconPreview = new System.Windows.Forms.PictureBox();
            this.buttonTest = new System.Windows.Forms.Button();
            this.labelHookHint = new System.Windows.Forms.Label();
            this.labelServiceStatus = new System.Windows.Forms.Label();
            this.buttonService = new System.Windows.Forms.Button();
            this.labelServiceHint = new System.Windows.Forms.Label();
            this.buttonSave = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.tabs.SuspendLayout();
            this.tabGeneral.SuspendLayout();
            this.tabAppearance.SuspendLayout();
            this.tabNotifications.SuspendLayout();
            this.tabService.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numInterval)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numProcessRetries)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numNetworkRetries)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numMaxRestarts)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCrashLimit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numShutdown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.iconPreview)).BeginInit();
            this.SuspendLayout();
            this.tabs.Controls.Add(this.tabGeneral);
            this.tabs.Controls.Add(this.tabAppearance);
            this.tabs.Controls.Add(this.tabNotifications);
            this.tabs.Controls.Add(this.tabService);
            this.tabs.Location = new System.Drawing.Point(8, 8);
            this.tabs.Name = "tabs";
            this.tabs.SelectedIndex = 0;
            this.tabs.Size = new System.Drawing.Size(324, 252);
            this.tabs.TabIndex = 0;
            this.tabGeneral.Controls.Add(this.labelInterval);
            this.tabGeneral.Controls.Add(this.numInterval);
            this.tabGeneral.Controls.Add(this.labelProcessRetries);
            this.tabGeneral.Controls.Add(this.numProcessRetries);
            this.tabGeneral.Controls.Add(this.labelNetworkRetries);
            this.tabGeneral.Controls.Add(this.numNetworkRetries);
            this.tabGeneral.Controls.Add(this.labelMaxRestarts);
            this.tabGeneral.Controls.Add(this.numMaxRestarts);
            this.tabGeneral.Controls.Add(this.labelCrashLimit);
            this.tabGeneral.Controls.Add(this.numCrashLimit);
            this.tabGeneral.Controls.Add(this.labelShutdown);
            this.tabGeneral.Controls.Add(this.numShutdown);
            this.tabGeneral.Controls.Add(this.checkTray);
            this.tabGeneral.Controls.Add(this.checkBoxLocalIps);
            this.tabGeneral.Controls.Add(this.buttonImport);
            this.tabGeneral.Location = new System.Drawing.Point(4, 22);
            this.tabGeneral.Name = "tabGeneral";
            this.tabGeneral.Padding = new System.Windows.Forms.Padding(3);
            this.tabGeneral.Size = new System.Drawing.Size(316, 226);
            this.tabGeneral.TabIndex = 0;
            this.tabGeneral.Text = "General";
            this.tabGeneral.UseVisualStyleBackColor = true;
            this.labelInterval.AutoSize = true;
            this.labelInterval.Location = new System.Drawing.Point(8, 14);
            this.labelInterval.Name = "labelInterval";
            this.labelInterval.Text = "Check interval (sec)";
            this.numInterval.Location = new System.Drawing.Point(244, 10);
            this.numInterval.Maximum = new decimal(new int[] { 30, 0, 0, 0 });
            this.numInterval.Minimum = new decimal(new int[] { 2, 0, 0, 0 });
            this.numInterval.Name = "numInterval";
            this.numInterval.Size = new System.Drawing.Size(60, 21);
            this.numInterval.TabIndex = 1;
            this.numInterval.Value = new decimal(new int[] { 5, 0, 0, 0 });
            this.labelProcessRetries.AutoSize = true;
            this.labelProcessRetries.Location = new System.Drawing.Point(8, 40);
            this.labelProcessRetries.Name = "labelProcessRetries";
            this.labelProcessRetries.Text = "Process check retries";
            this.numProcessRetries.Location = new System.Drawing.Point(244, 36);
            this.numProcessRetries.Maximum = new decimal(new int[] { 30, 0, 0, 0 });
            this.numProcessRetries.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this.numProcessRetries.Name = "numProcessRetries";
            this.numProcessRetries.Size = new System.Drawing.Size(60, 21);
            this.numProcessRetries.TabIndex = 2;
            this.numProcessRetries.Value = new decimal(new int[] { 3, 0, 0, 0 });
            this.labelNetworkRetries.AutoSize = true;
            this.labelNetworkRetries.Location = new System.Drawing.Point(8, 66);
            this.labelNetworkRetries.Name = "labelNetworkRetries";
            this.labelNetworkRetries.Text = "Network check retries";
            this.numNetworkRetries.Location = new System.Drawing.Point(244, 62);
            this.numNetworkRetries.Maximum = new decimal(new int[] { 60, 0, 0, 0 });
            this.numNetworkRetries.Minimum = new decimal(new int[] { 2, 0, 0, 0 });
            this.numNetworkRetries.Name = "numNetworkRetries";
            this.numNetworkRetries.Size = new System.Drawing.Size(60, 21);
            this.numNetworkRetries.TabIndex = 3;
            this.numNetworkRetries.Value = new decimal(new int[] { 15, 0, 0, 0 });
            this.labelMaxRestarts.AutoSize = true;
            this.labelMaxRestarts.Location = new System.Drawing.Point(8, 92);
            this.labelMaxRestarts.Name = "labelMaxRestarts";
            this.labelMaxRestarts.Text = "Max simultaneous restarts (0 = auto)";
            this.numMaxRestarts.Location = new System.Drawing.Point(244, 88);
            this.numMaxRestarts.Maximum = new decimal(new int[] { 64, 0, 0, 0 });
            this.numMaxRestarts.Name = "numMaxRestarts";
            this.numMaxRestarts.Size = new System.Drawing.Size(60, 21);
            this.numMaxRestarts.TabIndex = 4;
            this.labelCrashLimit.AutoSize = true;
            this.labelCrashLimit.Location = new System.Drawing.Point(8, 118);
            this.labelCrashLimit.Name = "labelCrashLimit";
            this.labelCrashLimit.Text = "Crashes per 5min before pause (0 = off)";
            this.numCrashLimit.Location = new System.Drawing.Point(244, 114);
            this.numCrashLimit.Maximum = new decimal(new int[] { 100, 0, 0, 0 });
            this.numCrashLimit.Name = "numCrashLimit";
            this.numCrashLimit.Size = new System.Drawing.Size(60, 21);
            this.numCrashLimit.TabIndex = 5;
            this.labelShutdown.AutoSize = true;
            this.labelShutdown.Location = new System.Drawing.Point(8, 144);
            this.labelShutdown.Name = "labelShutdown";
            this.labelShutdown.Text = "Clean shutdown timeout (sec, 0 = kill)";
            this.numShutdown.Location = new System.Drawing.Point(244, 140);
            this.numShutdown.Maximum = new decimal(new int[] { 120, 0, 0, 0 });
            this.numShutdown.Name = "numShutdown";
            this.numShutdown.Size = new System.Drawing.Size(60, 21);
            this.numShutdown.TabIndex = 7;
            this.checkTray.AutoSize = true;
            this.checkTray.Location = new System.Drawing.Point(10, 198);
            this.checkTray.Name = "checkTray";
            this.checkTray.TabIndex = 8;
            this.checkTray.Text = "Close to tray";
            this.checkTray.UseVisualStyleBackColor = true;
            this.checkBoxLocalIps.AutoSize = true;
            this.checkBoxLocalIps.Location = new System.Drawing.Point(130, 198);
            this.checkBoxLocalIps.Name = "checkBoxLocalIps";
            this.checkBoxLocalIps.TabIndex = 9;
            this.checkBoxLocalIps.Text = "List local IPs";
            this.checkBoxLocalIps.UseVisualStyleBackColor = true;
            this.buttonImport.Location = new System.Drawing.Point(230, 194);
            this.buttonImport.Name = "buttonImport";
            this.buttonImport.Size = new System.Drawing.Size(75, 22);
            this.buttonImport.TabIndex = 10;
            this.buttonImport.Text = "Import...";
            this.buttonImport.UseVisualStyleBackColor = true;
            this.buttonImport.Click += new System.EventHandler(this.buttonImport_Click);
            this.tabAppearance.Controls.Add(this.labelTheme);
            this.tabAppearance.Controls.Add(this.comboTheme);
            this.tabAppearance.Controls.Add(this.labelIcon);
            this.tabAppearance.Controls.Add(this.comboIcon);
            this.tabAppearance.Controls.Add(this.iconPreview);
            this.tabAppearance.Controls.Add(this.labelLanguage);
            this.tabAppearance.Controls.Add(this.comboLanguage);
            this.tabAppearance.Location = new System.Drawing.Point(4, 22);
            this.tabAppearance.Name = "tabAppearance";
            this.tabAppearance.Padding = new System.Windows.Forms.Padding(3);
            this.tabAppearance.Size = new System.Drawing.Size(316, 226);
            this.tabAppearance.TabIndex = 1;
            this.tabAppearance.Text = "Appearance";
            this.tabAppearance.UseVisualStyleBackColor = true;
            this.labelTheme.AutoSize = true;
            this.labelTheme.Location = new System.Drawing.Point(8, 18);
            this.labelTheme.Name = "labelTheme";
            this.labelTheme.Text = "Theme:";
            this.comboTheme.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboTheme.FormattingEnabled = true;
            this.comboTheme.Location = new System.Drawing.Point(60, 14);
            this.comboTheme.Name = "comboTheme";
            this.comboTheme.Size = new System.Drawing.Size(120, 20);
            this.comboTheme.TabIndex = 0;
            this.labelIcon.AutoSize = true;
            this.labelIcon.Location = new System.Drawing.Point(8, 56);
            this.labelIcon.Name = "labelIcon";
            this.labelIcon.Text = "Icon:";
            this.comboIcon.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboIcon.FormattingEnabled = true;
            this.comboIcon.Location = new System.Drawing.Point(60, 52);
            this.comboIcon.Name = "comboIcon";
            this.comboIcon.Size = new System.Drawing.Size(180, 20);
            this.comboIcon.TabIndex = 1;
            this.comboIcon.SelectedIndexChanged += new System.EventHandler(this.comboIcon_SelectedIndexChanged);
            this.iconPreview.Location = new System.Drawing.Point(252, 46);
            this.iconPreview.Name = "iconPreview";
            this.iconPreview.Size = new System.Drawing.Size(32, 32);
            this.iconPreview.TabStop = false;
            this.tabNotifications.Controls.Add(this.listViewHooks);
            this.tabNotifications.Controls.Add(this.buttonHookAdd);
            this.tabNotifications.Controls.Add(this.buttonHookEdit);
            this.tabNotifications.Controls.Add(this.buttonHookRemove);
            this.tabNotifications.Controls.Add(this.buttonTest);
            this.tabNotifications.Controls.Add(this.labelHookHint);
            this.tabNotifications.Location = new System.Drawing.Point(4, 22);
            this.tabNotifications.Name = "tabNotifications";
            this.tabNotifications.Padding = new System.Windows.Forms.Padding(3);
            this.tabNotifications.Size = new System.Drawing.Size(316, 226);
            this.tabNotifications.TabIndex = 2;
            this.tabNotifications.Text = "Web Hooks";
            this.tabNotifications.UseVisualStyleBackColor = true;
            this.buttonTest.Location = new System.Drawing.Point(8, 160);
            this.buttonTest.Name = "buttonTest";
            this.buttonTest.Size = new System.Drawing.Size(75, 23);
            this.buttonTest.TabIndex = 1;
            this.buttonTest.Text = "&Test";
            this.buttonTest.UseVisualStyleBackColor = true;
            this.buttonTest.Click += new System.EventHandler(this.buttonTest_Click);
            this.listViewHooks.FullRowSelect = true;
            this.listViewHooks.HideSelection = false;
            this.listViewHooks.Location = new System.Drawing.Point(8, 8);
            this.listViewHooks.MultiSelect = false;
            this.listViewHooks.Name = "listViewHooks";
            this.listViewHooks.Size = new System.Drawing.Size(298, 146);
            this.listViewHooks.UseCompatibleStateImageBehavior = false;
            this.listViewHooks.View = System.Windows.Forms.View.Details;
            this.listViewHooks.SelectedIndexChanged += new System.EventHandler(this.listViewHooks_SelectedIndexChanged);
            this.listViewHooks.DoubleClick += new System.EventHandler(this.buttonHookEdit_Click);
            this.buttonHookAdd.Location = new System.Drawing.Point(8, 160);
            this.buttonHookAdd.Name = "buttonHookAdd";
            this.buttonHookAdd.Size = new System.Drawing.Size(70, 23);
            this.buttonHookAdd.Text = "Add...";
            this.buttonHookAdd.UseVisualStyleBackColor = true;
            this.buttonHookAdd.Click += new System.EventHandler(this.buttonHookAdd_Click);
            this.buttonHookEdit.Location = new System.Drawing.Point(84, 160);
            this.buttonHookEdit.Name = "buttonHookEdit";
            this.buttonHookEdit.Size = new System.Drawing.Size(70, 23);
            this.buttonHookEdit.Text = "Edit...";
            this.buttonHookEdit.UseVisualStyleBackColor = true;
            this.buttonHookEdit.Click += new System.EventHandler(this.buttonHookEdit_Click);
            this.buttonHookRemove.Location = new System.Drawing.Point(160, 160);
            this.buttonHookRemove.Name = "buttonHookRemove";
            this.buttonHookRemove.Size = new System.Drawing.Size(70, 23);
            this.buttonHookRemove.Text = "Remove";
            this.buttonHookRemove.UseVisualStyleBackColor = true;
            this.buttonHookRemove.Click += new System.EventHandler(this.buttonHookRemove_Click);
            this.labelHookHint.Location = new System.Drawing.Point(8, 190);
            this.labelHookHint.Name = "labelHookHint";
            this.labelHookHint.Size = new System.Drawing.Size(298, 34);
            this.labelHookHint.Text = "Posts when the monitor starts, when a server is restarted, when crash-loop protection pauses a server, and when a schedule runs. Leave blank to disable.";
            this.tabService.Controls.Add(this.labelServiceStatus);
            this.tabService.Controls.Add(this.buttonService);
            this.tabService.Controls.Add(this.labelServiceHint);
            this.tabService.Location = new System.Drawing.Point(4, 22);
            this.tabService.Name = "tabService";
            this.tabService.Padding = new System.Windows.Forms.Padding(3);
            this.tabService.Size = new System.Drawing.Size(316, 226);
            this.tabService.TabIndex = 3;
            this.tabService.Text = "Service";
            this.tabService.UseVisualStyleBackColor = true;
            this.labelServiceStatus.AutoSize = true;
            this.labelServiceStatus.Location = new System.Drawing.Point(8, 14);
            this.labelServiceStatus.Name = "labelServiceStatus";
            this.labelServiceStatus.Text = "Status:";
            this.buttonService.Location = new System.Drawing.Point(8, 36);
            this.buttonService.Name = "buttonService";
            this.buttonService.Size = new System.Drawing.Size(140, 23);
            this.buttonService.TabIndex = 0;
            this.buttonService.Text = "Install service";
            this.buttonService.UseVisualStyleBackColor = true;
            this.buttonService.Click += new System.EventHandler(this.buttonService_Click);
            this.labelServiceHint.Location = new System.Drawing.Point(8, 72);
            this.labelServiceHint.Name = "labelServiceHint";
            this.labelServiceHint.Size = new System.Drawing.Size(298, 140);
            this.labelServiceHint.Text = "Runs the monitor as a Windows service so servers are watched and restarted without anyone logged in.\r\n\r\nServers launched by the service run as SYSTEM in session 0, so their console windows are not visible.\r\n\r\nInstalling starts the service and closes this window. Requires administrator rights.";
            this.buttonSave.Location = new System.Drawing.Point(176, 268);
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.Size = new System.Drawing.Size(75, 25);
            this.buttonSave.TabIndex = 1;
            this.buttonSave.Text = "&Save";
            this.buttonSave.UseVisualStyleBackColor = true;
            this.buttonSave.Click += new System.EventHandler(this.buttonSave_Click);
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new System.Drawing.Point(257, 268);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size(75, 25);
            this.buttonCancel.TabIndex = 2;
            this.buttonCancel.Text = "Cancel";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.buttonCancel;
            this.ClientSize = new System.Drawing.Size(340, 302);
            this.Controls.Add(this.tabs);
            this.Controls.Add(this.buttonSave);
            this.Controls.Add(this.buttonCancel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "OptionsForm";
            this.Text = "Options";
            this.Shown += new System.EventHandler(this.OptionsForm_Shown);
            this.tabs.ResumeLayout(false);
            this.tabGeneral.ResumeLayout(false);
            this.tabGeneral.PerformLayout();
            this.tabAppearance.ResumeLayout(false);
            this.tabAppearance.PerformLayout();
            this.tabNotifications.ResumeLayout(false);
            this.tabNotifications.PerformLayout();
            this.tabService.ResumeLayout(false);
            this.tabService.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numInterval)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numProcessRetries)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numNetworkRetries)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numMaxRestarts)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCrashLimit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numShutdown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.iconPreview)).EndInit();
            this.ResumeLayout(false);

        }

private hlsmx.ThemedTabControl tabs;
        private System.Windows.Forms.TabPage tabGeneral;
        private System.Windows.Forms.TabPage tabAppearance;
        private System.Windows.Forms.TabPage tabNotifications;
        private System.Windows.Forms.TabPage tabService;
        private System.Windows.Forms.Label labelInterval;
        private System.Windows.Forms.Label labelProcessRetries;
        private System.Windows.Forms.Label labelNetworkRetries;
        private System.Windows.Forms.Label labelMaxRestarts;
        private System.Windows.Forms.Label labelCrashLimit;
        private System.Windows.Forms.Label labelShutdown;
        private System.Windows.Forms.NumericUpDown numInterval;
        private System.Windows.Forms.NumericUpDown numProcessRetries;
        private System.Windows.Forms.NumericUpDown numNetworkRetries;
        private System.Windows.Forms.NumericUpDown numMaxRestarts;
        private System.Windows.Forms.NumericUpDown numCrashLimit;
        private System.Windows.Forms.NumericUpDown numShutdown;
        private System.Windows.Forms.CheckBox checkTray;
        private System.Windows.Forms.CheckBox checkBoxLocalIps;
        private System.Windows.Forms.Button buttonImport;
        private System.Windows.Forms.ListView listViewHooks;
        private System.Windows.Forms.Button buttonHookAdd;
        private System.Windows.Forms.Button buttonHookEdit;
        private System.Windows.Forms.Button buttonHookRemove;
        private System.Windows.Forms.Label labelLanguage;
        private System.Windows.Forms.ComboBox comboLanguage;
        private System.Windows.Forms.Label labelTheme;
        private System.Windows.Forms.ComboBox comboTheme;
        private System.Windows.Forms.Label labelIcon;
        private System.Windows.Forms.ComboBox comboIcon;
        private System.Windows.Forms.PictureBox iconPreview;
        private System.Windows.Forms.Button buttonTest;
        private System.Windows.Forms.Label labelHookHint;
        private System.Windows.Forms.Label labelServiceStatus;
        private System.Windows.Forms.Button buttonService;
        private System.Windows.Forms.Label labelServiceHint;
        private System.Windows.Forms.Button buttonSave;
        private System.Windows.Forms.Button buttonCancel;
    }
}
